function Q = get_quest(P)

Q = QuestCreate(P.quest.guess, ...
    P.quest.std, ...
    P.quest.pthreshold, ...
    P.quest.beta, ...
    P.quest.delta, ...
    P.quest.gamma);
Q.normalizePdf = 1;
Q = QuestRecompute(Q);
